<?php

defined('ABSPATH') || exit;

$title = trim((string) ($args['title'] ?? ''));
$heading_level = (int) ($args['heading_level'] ?? 3);
$heading_tag = 'h' . (in_array($heading_level, array(2, 3, 4, 5, 6), true) ? $heading_level : 3);
$url = (string) ($args['url'] ?? '');
$image = (string) ($args['image'] ?? '');
$excerpt = trim((string) ($args['excerpt'] ?? ''));
?>
<article <?php echo $args['wrapper_attributes']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes. ?>>
    <?php if ($image !== '') : ?>
        <div class="one-202x-content-card__media">
            <?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
        </div>
    <?php endif; ?>

    <div class="one-202x-content-card__content">
        <p class="one-202x-content-card__eyebrow">
            <time datetime="<?php echo esc_attr((string) ($args['published_datetime'] ?? '')); ?>"><?php echo esc_html((string) ($args['published_date'] ?? '')); ?></time>
        </p>
        <?php if ($title !== '') : ?>
            <<?php echo esc_attr($heading_tag); ?> class="one-202x-content-card__title">
                <?php if ($url !== '') : ?>
                    <a href="<?php echo esc_url($url); ?>"><?php echo esc_html($title); ?></a>
                <?php else : ?>
                    <?php echo esc_html($title); ?>
                <?php endif; ?>
            </<?php echo esc_attr($heading_tag); ?>>
        <?php endif; ?>

        <?php if ($excerpt !== '') : ?>
            <p class="one-202x-content-card__summary"><?php echo esc_html($excerpt); ?></p>
        <?php endif; ?>
    </div>
</article>
