<?php

defined('ABSPATH') || exit;

$post_id = absint($args['post_id'] ?? 0);
$values = class_exists(\One202x\Testimonials\TestimonialValues::class)
    ? (new \One202x\Testimonials\TestimonialValues())->all(
        $post_id,
        array(),
        array('source' => 'content_card')
    )
    : array();
$quote = trim((string) ($values['quote'] ?? ''));
$person_name = trim((string) ($values['person_name'] ?? ''));
$job_title = trim((string) ($values['job_title'] ?? ''));
$organisation = trim((string) ($values['organisation'] ?? ''));
$rating = isset($values['rating']) && is_numeric($values['rating'])
    ? min(5, max(1, (int) $values['rating']))
    : 0;
?>
<article <?php echo $args['wrapper_attributes']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes. ?>>
    <div class="one-202x-content-card__content">
        <?php if ($rating > 0) : ?>
            <p class="one-202x-content-card__rating">
                <?php
                printf(
                    /* translators: 1: testimonial rating, 2: maximum rating. */
                    esc_html__('%1$d out of %2$d stars', 'one-base-theme'),
                    $rating,
                    5
                );
                ?>
            </p>
        <?php endif; ?>

        <?php
        echo render_block(array(
            'blockName' => 'one-202x/quote',
            'attrs' => array(
                'quote' => esc_html($quote),
                'personName' => $person_name,
                'jobDescription' => implode(' · ', array_filter(array($job_title, $organisation))),
                'imageId' => (int) get_post_thumbnail_id($post_id),
            ),
            'innerBlocks' => array(),
            'innerHTML' => '',
            'innerContent' => array(),
        )); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Rendered theme block.
        ?>
    </div>
</article>
