<?php

defined('ABSPATH') || exit;

$post_id = absint($args['post_id'] ?? 0);
$title = trim((string) ($args['title'] ?? ''));
$heading_level = (int) ($args['heading_level'] ?? 3);
$heading_tag = 'h' . (in_array($heading_level, array(2, 3, 4, 5, 6), true) ? $heading_level : 3);
$url = (string) ($args['url'] ?? '');
$image = (string) ($args['image'] ?? '');
$excerpt = trim((string) ($args['excerpt'] ?? ''));
$values = class_exists(\One202x\TeamMembers\TeamMemberValues::class)
    ? (new \One202x\TeamMembers\TeamMemberValues())->all(
        $post_id,
        array(),
        array('source' => 'content_card')
    )
    : array();
$job_title = trim((string) ($values['job_title'] ?? ''));
$department = trim((string) ($values['department'] ?? ''));
$email = isset($values['email'])
    ? sanitize_email((string) $values['email'])
    : '';
$telephone = trim((string) ($values['telephone'] ?? ''));
$telephone_href = preg_replace('/[^0-9+]/', '', $telephone) ?: '';
$linkedin_url = trim((string) ($values['linkedin_url'] ?? ''));
?>
<article <?php echo $args['wrapper_attributes']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes. ?>>


    <div class="one-202x-content-card__content">
        <?php if ($title !== '') : ?>
            <<?php echo esc_attr($heading_tag); ?> class="one-202x-content-card__title">
                <a href="<?php echo esc_url($url); ?>"><?php echo esc_html($title); ?></a>
            </<?php echo esc_attr($heading_tag); ?>>
        <?php endif; ?>

        <?php if ($job_title !== '' || $department !== '') : ?>
            <p class="one-202x-content-card__meta">
                <?php echo esc_html(implode(' · ', array_filter(array($job_title, $department)))); ?>
            </p>
        <?php endif; ?>

        <?php if ($excerpt !== '') : ?>
            <p class="one-202x-content-card__summary"><?php echo esc_html($excerpt); ?></p>
        <?php endif; ?>

        <?php if ($email !== '' || $telephone !== '' || $linkedin_url !== '') : ?>
            <ul class="one-202x-content-card__contacts">
                <?php if ($email !== '') : ?>
                    <li><a href="<?php echo esc_attr('mailto:' . $email); ?>"><?php echo esc_html($email); ?></a></li>
                <?php endif; ?>
                <?php if ($telephone !== '' && $telephone_href !== '') : ?>
                    <li><a href="<?php echo esc_attr('tel:' . $telephone_href); ?>"><?php echo esc_html($telephone); ?></a></li>
                <?php endif; ?>
                <?php if ($linkedin_url !== '') : ?>
                    <li><a href="<?php echo esc_url($linkedin_url); ?>"><?php esc_html_e('LinkedIn', 'one-base-theme'); ?></a></li>
                <?php endif; ?>
            </ul>
        <?php endif; ?>
    </div>
    <?php if ($image !== '') : ?>
        <div class="one-202x-content-card__media">
            <?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
        </div>
    <?php endif; ?>
</article>
