<?php

defined('ABSPATH') || exit;

$post_id = absint($args['post_id'] ?? 0);
$title = trim((string) ($args['title'] ?? ''));
$heading_level = (int) ($args['heading_level'] ?? 3);
$heading_tag = 'h' . (in_array($heading_level, array(2, 3, 4, 5, 6), true) ? $heading_level : 3);
$url = (string) ($args['url'] ?? '');
$image = (string) ($args['image'] ?? '');
$excerpt = trim((string) ($args['excerpt'] ?? ''));
$values = class_exists(\One202x\Events\EventValues::class)
    ? (new \One202x\Events\EventValues())->all(
        $post_id,
        array(),
        array('source' => 'content_card')
    )
    : array();
$start_date = trim((string) ($values['start_date'] ?? ''));
$end_date = trim((string) ($values['end_date'] ?? ''));
$start_date_iso = (string) ($values['start_date_iso'] ?? '');
$end_date_iso = (string) ($values['end_date_iso'] ?? '');
$venue = trim((string) ($values['venue'] ?? ''));
$price = trim((string) ($values['price'] ?? ''));
$booking_url = trim((string) ($values['booking_url'] ?? ''));
$action_url = $booking_url !== '' ? $booking_url : $url;
$action_label = $booking_url !== ''
    ? __('Book this event', 'one-base-theme')
    : __('View event', 'one-base-theme');
?>
<article <?php echo $args['wrapper_attributes']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes. ?>>
    <?php if ($image !== '') : ?>
        <div class="one-202x-content-card__media">
            <?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
        </div>
    <?php endif; ?>

    <div class="one-202x-content-card__content">
        <?php if ($start_date !== '') : ?>
            <p class="one-202x-content-card__eyebrow">
                <?php if ($start_date_iso !== '') : ?>
                    <time datetime="<?php echo esc_attr($start_date_iso); ?>"><?php echo esc_html($start_date); ?></time>
                <?php else : ?>
                    <span><?php echo esc_html($start_date); ?></span>
                <?php endif; ?>
                <?php if ($end_date !== '') : ?>
                    <span>–</span>
                    <?php if ($end_date_iso !== '') : ?>
                        <time datetime="<?php echo esc_attr($end_date_iso); ?>"><?php echo esc_html($end_date); ?></time>
                    <?php else : ?>
                        <span><?php echo esc_html($end_date); ?></span>
                    <?php endif; ?>
                <?php endif; ?>
            </p>
        <?php endif; ?>

        <?php if ($title !== '') : ?>
            <<?php echo esc_attr($heading_tag); ?> class="one-202x-content-card__title">
                <a href="<?php echo esc_url($url); ?>"><?php echo esc_html($title); ?></a>
            </<?php echo esc_attr($heading_tag); ?>>
        <?php endif; ?>

        <?php if ($venue !== '' || $price !== '') : ?>
            <p class="one-202x-content-card__meta">
                <?php echo esc_html(implode(' · ', array_filter(array($venue, $price)))); ?>
            </p>
        <?php endif; ?>

        <?php if ($excerpt !== '') : ?>
            <p class="one-202x-content-card__summary"><?php echo esc_html($excerpt); ?></p>
        <?php endif; ?>

        <?php if ($action_url !== '') : ?>
            <a class="one-202x-content-card__link" href="<?php echo esc_url($action_url); ?>">
                <?php echo esc_html($action_label); ?>
                <?php if ($title !== '') : ?>
                    <span class="screen-reader-text">: <?php echo esc_html($title); ?></span>
                <?php endif; ?>
            </a>
        <?php endif; ?>
    </div>
</article>
