<?php

defined('ABSPATH') || exit;

$post_id = absint($args['post_id'] ?? 0);
$title = trim((string) ($args['title'] ?? ''));
$heading_level = (int) ($args['heading_level'] ?? 3);
$heading_tag = 'h' . (in_array($heading_level, array(2, 3, 4, 5, 6), true) ? $heading_level : 3);
$url = (string) ($args['url'] ?? '');
$image = (string) ($args['image'] ?? '');
$excerpt = trim((string) ($args['excerpt'] ?? ''));
$values = class_exists(\One202x\Services\ServiceValues::class)
    ? (new \One202x\Services\ServiceValues())->all(
        $post_id,
        array(),
        array('source' => 'content_card')
    )
    : array();
$summary = isset($values['summary']) && is_string($values['summary'])
    ? trim($values['summary'])
    : $excerpt;
$call_to_action = isset($values['call_to_action'])
    && is_array($values['call_to_action'])
        ? $values['call_to_action']
        : array();
$action_url = isset($call_to_action['url'])
    && is_string($call_to_action['url'])
        ? $call_to_action['url']
        : $url;
$action_label = isset($call_to_action['title'])
    && is_string($call_to_action['title'])
    && trim($call_to_action['title']) !== ''
        ? $call_to_action['title']
        : __('View service', 'one-base-theme');
$action_target = isset($call_to_action['target'])
    && $call_to_action['target'] === '_blank'
        ? '_blank'
        : '';
?>
<article <?php echo $args['wrapper_attributes']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes. ?>>
    <?php if ($image !== '') : ?>
        <div class="one-202x-content-card__media">
            <?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
        </div>
    <?php endif; ?>

    <div class="one-202x-content-card__content">
        <?php if ($title !== '') : ?>
            <<?php echo esc_attr($heading_tag); ?> class="one-202x-content-card__title">
                <a href="<?php echo esc_url($url); ?>"><?php echo esc_html($title); ?></a>
            </<?php echo esc_attr($heading_tag); ?>>
        <?php endif; ?>

        <?php if ($summary !== '') : ?>
            <div class="one-202x-content-card__summary"><?php echo wp_kses_post($summary); ?></div>
        <?php endif; ?>

        <?php if ($action_url !== '') : ?>
            <a
                class="one-202x-content-card__link"
                href="<?php echo esc_url($action_url); ?>"
                <?php if ($action_target !== '') : ?>
                    target="_blank"
                    rel="noopener noreferrer"
                <?php endif; ?>
            >
                <?php echo esc_html($action_label); ?>
                <?php if ($title !== '') : ?>
                    <span class="screen-reader-text">: <?php echo esc_html($title); ?></span>
                <?php endif; ?>
                <?php if ($action_target === '_blank') : ?>
                    <span class="screen-reader-text"> <?php esc_html_e('(opens in a new tab)', 'one-base-theme'); ?></span>
                <?php endif; ?>
            </a>
        <?php endif; ?>
    </div>
</article>
