<?php

defined('ABSPATH') || exit;

$title = (string) ($args['title'] ?? '');
$url = (string) ($args['url'] ?? '');
$heading_level = (int) ($args['heading_level'] ?? 3);
$heading_tag = 'h' . (in_array($heading_level, array(2, 3, 4, 5, 6), true) ? $heading_level : 3);
?>
<article <?php echo $args['wrapper_attributes']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes. ?>>
    <div class="one-202x-content-card__content">
        <<?php echo esc_attr($heading_tag); ?> class="one-202x-content-card__title">
            <?php if ($url !== '') : ?>
                <a href="<?php echo esc_url($url); ?>"><?php echo esc_html($title); ?></a>
            <?php else : ?>
                <?php echo esc_html($title); ?>
            <?php endif; ?>
        </<?php echo esc_attr($heading_tag); ?>>
        <p class="one-202x-content-card__summary"><?php esc_html_e('A password is required to view this content.', 'one-base-theme'); ?></p>
    </div>
</article>
