<?php

defined('ABSPATH') || exit;

$post_id = absint($args['post_id'] ?? 0);
$title = trim((string) ($args['title'] ?? ''));
$heading_level = (int) ($args['heading_level'] ?? 3);
$heading_tag = 'h' . (in_array($heading_level, array(2, 3, 4, 5, 6), true) ? $heading_level : 3);
$url = (string) ($args['url'] ?? '');
$image = (string) ($args['image'] ?? '');
$excerpt = trim((string) ($args['excerpt'] ?? ''));
$values = class_exists(\One202x\CaseStudies\CaseStudyValues::class)
    ? (new \One202x\CaseStudies\CaseStudyValues())->all(
        $post_id,
        array(),
        array('source' => 'content_card')
    )
    : array();
$client_name = trim((string) ($values['client_name'] ?? ''));
$summary = isset($values['summary']) && is_string($values['summary'])
    ? trim($values['summary'])
    : $excerpt;
?>
<article <?php echo $args['wrapper_attributes']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by get_block_wrapper_attributes. ?>>
    <?php if ($image !== '') : ?>
        <div class="one-202x-content-card__media">
            <a href="<?php echo esc_url($url); ?>" tabindex="-1" aria-hidden="true">
                <?php echo $image; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
            </a>
        </div>
    <?php endif; ?>

    <div class="one-202x-content-card__content">
        <?php if ($client_name !== '') : ?>
            <p class="one-202x-content-card__eyebrow"><?php echo esc_html($client_name); ?></p>
        <?php endif; ?>

        <?php if ($title !== '') : ?>
            <<?php echo esc_attr($heading_tag); ?> class="one-202x-content-card__title">
                <a href="<?php echo esc_url($url); ?>"><?php echo esc_html($title); ?></a>
            </<?php echo esc_attr($heading_tag); ?>>
        <?php endif; ?>

        <?php if ($summary !== '') : ?>
            <div class="one-202x-content-card__summary"><?php echo wp_kses_post($summary); ?></div>
        <?php endif; ?>

        <?php if ($url !== '') : ?>
            <a class="one-202x-content-card__link" href="<?php echo esc_url($url); ?>">
                <?php esc_html_e('View case study', 'one-base-theme'); ?>
                <?php if ($title !== '') : ?>
                    <span class="screen-reader-text">: <?php echo esc_html($title); ?></span>
                <?php endif; ?>
            </a>
        <?php endif; ?>
    </div>
</article>
